services:
  postgres:
    image: postgres:18.3-alpine3.22
    container_name: cookbook-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cookbook
      POSTGRES_PASSWORD: cookbook
      POSTGRES_DB: cookbook_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - distributed-cookbook
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cookbook -d cookbook_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_data:

networks:
  distributed-cookbook:
    external: true
