apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalog-service
  labels:
    app: catalog-service
    cookbook.service: catalog-service
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels: { app: catalog-service }
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
